version: '3.9'

services:
  database:
    image: mongo
    container_name: spotify-database
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=spotify
    networks: 
      - spotify
    volumes:
      - database:/data/db
      - ./dataset:/usr/dataset:ro
      - ./config/1-import-data.sh:/docker-entrypoint-initdb.d/1-import.sh:ro
      - ./config/2-process-data.js:/docker-entrypoint-initdb.d/2-process.js:ro

  interface:
    image: metabase/metabase
    container_name: spotify-metabase
    volumes:
      - config:/metabase.db
    networks: 
      - spotify
    ports:
      - 3000:3000

networks:
  spotify:
    driver: bridge
    name: spotify

volumes:
  database:
    name: spotify-db
  config:
    name: spotify-metabase